# Generated by Django 2.2.6 on 2022-01-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20211016_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='здесь напишите ваш пост'),
        ),
    ]
